name: WolkieTalkie
options:
  bundleIdPrefix: com.wolkie
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: Info.plist

targets:
  WolkieTalkie:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wolkie.talkie
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
    info:
      path: Info.plist
      properties:
        CFBundleName: WolkieTalkie
        CFBundleDisplayName: WolkieTalkie
        CFBundleIdentifier: com.wolkie.talkie
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: WolkieTalkie
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIUserInterfaceStyle: Dark
        NSBluetoothAlwaysUsageDescription: "需要蓝牙权限来发现附近的对讲设备"
        NSBluetoothPeripheralUsageDescription: "需要蓝牙权限来发现附近的对讲设备"
        NSMicrophoneUsageDescription: "需要麦克风权限来进行语音对讲"
        NSLocalNetworkUsageDescription: "需要本地网络权限来连接附近设备"
        NSNearbyInteractionUsageDescription: "需要 UWB 超宽带权限来检测设备距离"
        UIBackgroundModes:
          - audio
          - bluetooth-central
